[ruleset]
overwrite_original_rules = true

[[rulesets]]
group = "ğŸ†AdBlock"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Reject.list"

[[rulesets]]
group = "ğŸ¯å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Special.list"
[[rulesets]]
group = "ğŸ“ºNetflix"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Netflix.list"

[[rulesets]]
group = "ğŸµSpotify"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Spotify.list"

#[[rulesets]]
#group = "ğŸ¥å›½é™…åª’ä½“"
#ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/YouTube%20Music.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/YouTube.list"

[[rulesets]]
group = "ğŸ¯å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Bilibili.list"

[[rulesets]]
group = "ğŸ¯å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/IQ.list"

[[rulesets]]
group = "ğŸ¯å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/IQIYI.list"

[[rulesets]]
group = "ğŸ¯å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Letv.list"

#[[rulesets]]
#group = "ğŸ¯å…¨çƒç›´è¿"
#ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/MOO.list"

[[rulesets]]
group = "ğŸ¯å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Netease%20Music.list"

[[rulesets]]
group = "ğŸ¯å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Tencent%20Video.list"

[[rulesets]]
group = "ğŸ¯å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Youku.list"

[[rulesets]]
group = "ğŸ¯å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/WeTV.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/ABC.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Abema%20TV.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Amazon.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Apple%20News.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Apple%20TV.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Bahamut.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/BBC%20iPlayer.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/DAZN.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Discovery%20Plus.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Disney%20Plus.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/encoreTVB.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Fox%20Now.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Fox%2B.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/HBO%20Go.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/HBO%20Max.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Hulu%20Japan.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Hulu.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Japonx.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/JOOX.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/KKBOX.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/KKTV.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Line%20TV.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/myTV%20SUPER.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Pandora.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/PBS.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Pornhub.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Soundcloud.list"

[[rulesets]]
group = "ğŸ¥å›½é™…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/ViuTV.list"

[[rulesets]]
group = "ğŸ‡ºğŸ‡²ç¾å›½èŠ‚ç‚¹"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Telegram/TelegramUS.list"

[[rulesets]]
group = "ğŸ‡¸ğŸ‡¬ç‹®åŸèŠ‚ç‚¹"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Telegram/TelegramSG.list"

[[rulesets]]
group = "ğŸ‡ªğŸ‡ºæ¬§æ´²èŠ‚ç‚¹"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Telegram/TelegramNL.list"

[[rulesets]]
group = "ğŸ‡­ğŸ‡°é¦™æ¸¯èŠ‚ç‚¹"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Telegram.list"

#[[rulesets]]
#group = "ğŸ®æ¸¸æˆå¹³å°"
#ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list"

#[[rulesets]]
#group = "ğŸ®æ¸¸æˆå¹³å°"
#ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list"

[[rulesets]]
group = "ğŸ®æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Steam.list"

[[rulesets]]
group = "ğŸ§²Speedtest"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Speedtest.list"

[[rulesets]]
group = "ğŸ’³PayPal"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/PayPal.list"

[[rulesets]]
group = "â“‚ï¸å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Microsoft.list"

[[rulesets]]
group = "ğŸˆèŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Proxy.list"

[[rulesets]]
group = "ğŸ¯å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Domestic.list"

[[rulesets]]
group = "ğŸè‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Apple.list"

[[rulesets]]
group = "ğŸ“¢è°·æ­ŒFCM"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Google%20FCM.list"

[[rulesets]]
group = "ğŸ“æ–‡çŒ®æŸ¥è¯¢"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Scholar.list"

[[rulesets]]
group = "ğŸ¯å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Domestic%20IPs.list"

[[rulesets]]
group = "ğŸ¯å…¨çƒç›´è¿"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/LAN.yaml"

[[rulesets]]
group = "ğŸ¯å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸæ¼ç½‘ä¹‹é±¼"
ruleset = "[]MATCH"

[[custom_groups]]
name = "ğŸˆèŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]ğŸ‡­ğŸ‡°é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µæ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡ªğŸ‡ºæ¬§æ´²èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡²ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡·éŸ©å›½èŠ‚ç‚¹", ".*"]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡°é¦™æ¸¯èŠ‚ç‚¹"
type = "url-test"
rule = "^((?!ç‹—).)*(æ¸¯|HK|Hong Kong)((?!ç‹—).)*$"
url = "http://www.qualcomm.cn/generate_204"
interval = 120
tolerance = 30
lazy = true

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³å°æ¹¾èŠ‚ç‚¹"
type = "url-test"
rule = "(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)"
url = "http://www.qualcomm.cn/generate_204"
interval = 300
tolerance = 40
lazy = true

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µæ—¥æœ¬èŠ‚ç‚¹"
type = "url-test"
rule = "(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan)"
url = "http://www.qualcomm.cn/generate_204"
interval = 300
tolerance = 40
lazy = true

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ç‹®åŸèŠ‚ç‚¹"
type = "load-balance"
rule = "(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)"
url = "http://www.qualcomm.cn/generate_204"
strategy = "consistent-hashing"
interval = 120
lazy = true

[[custom_groups]]
name = "ğŸ‡ªğŸ‡ºæ¬§æ´²èŠ‚ç‚¹"
type = "load-balance"
rule = "(æ³•å›½|å¾·å›½|è‹±å›½|ä¿„ç½—æ–¯|æ¯”åˆ©æ—¶|æ„å¤§åˆ©|è·å…°|å¥¥åœ°åˆ©|ä¸¹éº¦|æŒªå¨|èŠ¬å…°|ç‘å…¸)"
url = "http://www.qualcomm.cn/generate_204"
strategy = "consistent-hashing"
interval = 120
lazy = true

[[custom_groups]]
name = "ğŸ‡ºğŸ‡²ç¾å›½èŠ‚ç‚¹"
type = "load-balance"
rule = "(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)"
url = "http://www.qualcomm.cn/generate_204"
strategy = "consistent-hashing"
interval = 120
lazy = true

[[custom_groups]]
name = "ğŸ‡°ğŸ‡·éŸ©å›½èŠ‚ç‚¹"
type = "url-test"
rule = "(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)"
url = "http://www.qualcomm.cn/generate_204"
interval = 300
tolerance = 40
lazy = true

# custom_proxy_group=å¥ˆé£èŠ‚ç‚¹`select`(NF|å¥ˆé£|è§£é”|Netflix|NETFLIX|Media)

[[custom_groups]]
name = "ğŸ†AdBlock"
type = "select"
rule = ["[]DIRECT", "[]REJECT"]
# disable_udp = false


[[custom_groups]]
name = "ğŸ“ºNetflix"
type = "select"
rule = ".*"

[[custom_groups]]
name = "ğŸµSpotify"
type = "select"
rule = ".*"

[[custom_groups]]
name = "ğŸ¥å›½é™…åª’ä½“"
type = "select"
rule = ["[]ğŸˆèŠ‚ç‚¹é€‰æ‹©", ".*"]

[[custom_groups]]
name = "ğŸ®æ¸¸æˆå¹³å°"
type = "select"
rule = ["[]DIRECT", "[]ğŸˆèŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ§²Speedtest"
type = "select"
rule = ["[]DIRECT", "[]ğŸˆèŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ’³PayPal"
type = "select"
rule = ["[]DIRECT", "[]ğŸˆèŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸè‹¹æœæœåŠ¡"
type = "select"
rule = ["[]DIRECT", "[]ğŸˆèŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ“¢è°·æ­ŒFCM"
type = "select"
rule = ["[]DIRECT", "[]ğŸˆèŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ“æ–‡çŒ®æŸ¥è¯¢"
type = "select"
rule = ["[]DIRECT", "[]ğŸˆèŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ¯å…¨çƒç›´è¿"
type = "select"
rule = ["[]DIRECT", "[]ğŸˆèŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸŸæ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]DIRECT", "[]ğŸˆèŠ‚ç‚¹é€‰æ‹©"]

